name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Injecting environment vars
      run: |
        echo "${{ secrets.TEST_SECRETS }}" >> .env
    - name: Building Docker containers
      run: |
        sudo docker compose up -d --build
        sudo docker compose logs

  deploy:
    name: Deploying on EC2 via SSH
    if: ${{ github.event_name == 'push' }}
    needs: [build-test]
    runs-on: self-hosted
    steps:
    - name: Deploying Application on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: "18.222.31.28"
        username: "ubuntu"
        key: |
          -----BEGIN RSA PRIVATE KEY-----
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCLw/aBC/Y79Nb8oyio8t15wsZdjuopvbgGl34PfgcR11RnLJUMnbSjErJhA6C7q3i2PKGG+21SjtKboYkE/EmBbrZ+53ENPnS0aqDX2XwP8T+DYCftouxFjURE3u6wOHGjJKj8jHMa40NZkQvLJsLwS8vnRWyBASBY+pyXFR6UwF93W++ExLwFu8GUBvtvYfWpQc/tmyScKodOlUG1MzVYonN9YLfsrB1JPJu9CJQAO6zrOwtERh3qFVTVO9Y1kTRsQ5AaHUGN3JxMQgPPrQvMtykDtnTmQynT4EkVBiZOFm2WqYnUKCEeM3kPH2A4/ndciI0TKIsWRFTcVcS1WT5t8bN8qytmI9jFqmYZBu2LXFfJNoDdeGkjf/FLDiOKzzpXCPVFcjDq1mqgy0JwkIqqCWuPtb1JgOpiY3j/qHf8fRb2LdejeVtv83HRm/zXzMIoHJIOYcbRGIH+mw2t3+3OPlkpDJZhewY6lxLDGFslCBfQT4groTV8P8SNbgxHiKYk9lthzXfXDCnArzmpqixd/liiJ1cWus8Q75+4Nu/oNdn11IeYaibCQYtKQ9wGC3c5RIYBZ4J/ANEMQlW2868gRGfKfzZv0ocjZdeqPiRDFlH554K9bE61t56L8DvK0jnoML7QmpP90JRGASm58HFiuOMcM8/epB9wfJVLsYXRcQ== matias.saantiago@gmail.com
          -----END RSA PRIVATE KEY-----
        passphrase: "djangosocial"
        script: |
          cd ~/.scripts
          ./docker-ec2-deploy.sh
